services:
  - type: web
    name: modular-bot-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn engine.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: false
